[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/1jmdev/bevykit"
rust-version = "1.89"
authors = ["Matyas Kumzak"]
keywords = ["bevy", "gamedev", "ui", "input", "game-engine"]
categories = ["game-development", "game-engines"]

[workspace.dependencies]
bevy = { version = "0.19.1", default-features = false }

bevykit = { path = "crates/bevykit", version = "0.1.0" }
bevykit_animation = { path = "crates/bevykit_animation", version = "0.1.0" }
bevykit_assets = { path = "crates/bevykit_assets", version = "0.1.0" }
bevykit_audio = { path = "crates/bevykit_audio", version = "0.1.0" }
bevykit_content = { path = "crates/bevykit_content", version = "0.1.0" }
bevykit_core = { path = "crates/bevykit_core", version = "0.1.0" }
bevykit_feedback = { path = "crates/bevykit_feedback", version = "0.1.0" }
bevykit_input = { path = "crates/bevykit_input", version = "0.1.0" }
bevykit_localization = { path = "crates/bevykit_localization", version = "0.1.0" }
bevykit_macros = { path = "crates/bevykit_macros", version = "0.1.0" }
bevykit_mobile = { path = "crates/bevykit_mobile", version = "0.1.0" }
bevykit_save = { path = "crates/bevykit_save", version = "0.1.0" }
bevykit_settings = { path = "crates/bevykit_settings", version = "0.1.0" }
bevykit_storage = { path = "crates/bevykit_storage", version = "0.1.0" }
bevykit_tween = { path = "crates/bevykit_tween", version = "0.1.0" }
bevykit_ui = { path = "crates/bevykit_ui", version = "0.1.0" }

directories = "6.0"
fastrand = "2.3"
intl_pluralrules = "7.0"
proc-macro-crate = "3.3"
proc-macro2 = "1.0"
quote = "1.0"
ron = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smallvec = { version = "1.13", features = ["union", "const_generics"] }
syn = { version = "2.0", features = ["full", "extra-traits"] }
thiserror = "2.0"
toml = "0.9"
unic-langid = "0.9"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
